### ISSUE TITLE
Failed to find plugin to handle accessory ROOT

### ISSUE THREAD

**Issue by NathanDai** [moritzmhmk/homebridge-camera-rpi#10]
[2018-1-20 16:11:05] [rpi-camera] Initializing rpi-camera platform...
Load homebridge-mi-aqara.MiAqaraPlatform
Failed to find plugin to handle accessory ROOT

**Comment by NathanDai** [comment]
-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
ffmpeg ffmpeg version 3.2.9-1~deb9u1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100

ffmpeg [video4linux2,v4l2 @ 0x18a13c0] The V4L2 driver changed the video from 480x270 to 320x240
[video4linux2,v4l2 @ 0x18a13c0] Cannot find a proper format for codec 'mjpeg' (id 8), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at src/libavdevice/v4l2.c:806

**Comment by moritzmhmk** [comment]
What does your homebridge config look like?
