### ISSUE TITLE
How to set the item to start automatically

### ISSUE THREAD

**Issue by cuiyihaohao** [moritzmhmk/homebridge-camera-rpi#11]
When I use ssh to execute the command ‘homebridge’，This program runs very well.but when i follow [https://timleland.com/setup-homebridge-to-start-on-bootup/](url) this project can't start with the raspberry pi and the homebridge works normally.so i must login in ssh to run 'sudo systemctl stop homebridge' and run homebridge. so that i can use camera again.

**Comment by moritzmhmk** [comment]
The user `homebridge` needs to be part of the `video` group to access the camera.

**Comment by cuiyihaohao** [comment]
thank you very much.
