### ISSUE TITLE
No video update

### ISSUE THREAD

**Issue by juergen4mueller** [moritzmhmk/homebridge-camera-rpi#13]
I Use your plugin and had one day a working video transmission to Home-App.
I tried to add another plugin and had to change config.json.
After that it was not possible to get a new picture in Home-App, even after undo changes.

Do you have any idea what to setup.
Here the log from within  Homebridge 

ffmpeg /dev/video0: Device or resource busy

--set-ctrl video_bitrate=299000
-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -vcodec copy -an -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params inn7HeK68B3e5f7V70VmvUCPTHRbaOXEyUDaeELU srtp://192.168.55.40:65276?rtcpport=65276&localrtcpport=65276&pkt_size=1378
ffmpeg ffmpeg version 3.2.10-1~deb9u1+rpt1
ffmpeg  Copyright (c) 2000-2018 the FFmpeg developers
ffmpeg 
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100

**Comment by skrollme** [comment]
The other software - whatever it is - is still using the camera **/dev/video0** and so the homebridge-plugin cannot use it. See first line of your debug-log.
Without further tools it is not possible to use the same video-device with different software/tools at the same time.
So exit the other video-software and the video should start working in homebridge/homekit again.

**Comment by moritzmhmk** [comment]
can this be closed?

**Comment by juergen4mueller** [comment]
I did not find any other software using the camera.
After some reboots (without changing anything) the problem never occurred.
