### ISSUE TITLE
Not shown in HomeKit app

### ISSUE THREAD

**Issue by Suplanus** [moritzmhmk/homebridge-camera-rpi#14]
I have setup followed:

config.json:
```json
    {
      "platform": "rpi-camera",
      "cameras": [{"name": "Pi Camera"}]
    }
```

log:
```
[2018-2-17 15:09:28] Loaded plugin: homebridge-camera-rpi
[2018-2-17 15:09:28] Registering platform 'homebridge-camera-rpi.rpi-camera'
...
[2018-2-17 15:09:31] [rpi-camera] Initializing rpi-camera platform...
...
[2018-2-17 15:09:32] Pi Camera is running on port 44287.
```

But there is no Device in HomeKit. I removed the homebridge from devices and re-added it. But the camera dont show up. Bcm and ffmpeg is set / installed.

**Comment by moritzmhmk** [comment]
The camera is not a device that is managed by the bridge device "homebridge" but another "top level" device itself. So you need to add it like you did add "homebridge" (code is the same).

**Comment by Suplanus** [comment]
Ahh, ok.
I have read this in the readme... but i was thinking that the device should be added with the bridge.
Thanks!
