### ISSUE TITLE
Error setting bitrate

### ISSUE THREAD

**Issue by Paulg5678** [moritzmhmk/homebridge-camera-rpi#16]
Hello,
I am seeing the following in my homebridge log and not getting any response in homekit from my raspi camera, can anyone please advise? Thanks.

--set-ctrl rotate=0
--set-ctrl vertical_flip=0
--set-ctrl horizontal_flip=0
error while setting bitrate: spawn v4l2-ctl ENOENT
error while setting bitrate: spawn v4l2-ctl ENOENT
error while setting bitrate: spawn v4l2-ctl ENOENT
[2018-2-28 06:01:07] Pi Camera is running on port 34369.

**Comment by Paulg5678** [comment]
Hate to be a bother, but has anyone looked into this yet?   I've tried commenting out what seemed to be the offending lines of code, but to no avail.

Any advice would be greatly appreciated.  Thanks.

**Comment by moritzmhmk** [comment]
Can you execute `v4l2-ctl`?

**Comment by Paulg5678** [comment]
Just by itself with no options/args?

**Comment by moritzmhmk** [comment]
👍

**Comment by Paulg5678** [comment]
Thanks, i'm at work right now, but will try it out when i get home.

**Comment by Paulg5678** [comment]
When i run that with no args, i get a list of the General/Common options

**Comment by Paulg5678** [comment]
I'm sorry, but I'm new to linux.  How can I find out which user is executing homebridge and its associated group membership?

**Comment by Paulg5678** [comment]
I tried to set the bitrate with the command line 
 v4l2-ctl --set-ctrl video_bitrate=300000

and I get the error: Failed to open /dev/video0: No such file or directory

**Comment by moritzmhmk** [comment]
Looks like you didnt load the `bcm2835-v4l2` module (see README) it must be loaded every boot or added to the list of automatically loaded modules.

**Comment by Paulg5678** [comment]
I have added that module.  So I removed it and re-added.  I am now seeing a different error when the script tries to run the ffmpeg commands, I will get you the exact error message this evening.  Thanks for working with me here.
