### ISSUE TITLE
Disable 1080p due to cropping?

### ISSUE THREAD

**Issue by wildbomb** [moritzmhmk/homebridge-camera-rpi#2]
First of all, this is working perfectly! Nice job!

I noticed that when streaming from my iPad, the Home app requests 1080p video (the iPhone always asks for 720p) which streams OK, but shows a cropped picture (see [http://www.lewisroberts.com/2015/05/15/raspberry-pi-mjpeg-at-30fps/](http://www.lewisroberts.com/2015/05/15/raspberry-pi-mjpeg-at-30fps/))
The problem is that the snapshots are requested using a lower resolution, so when switching from a snapshot to live video, there is a jump in the frame.
I disabled 1080p and 960p and now it transitions perfectly between snapshot and stream with a 720p resolution.

Maybe add an option to define the max resolution? or disable 1080p altogether? What do you think?

**Comment by moritzmhmk** [comment]
thanks for pointing that out - fixed it (6fd6954a9c5bcd8de6c63ec3fc64021a9d6ecf4b)
