### ISSUE TITLE
Can't view camera simultaneously from two sources

### ISSUE THREAD

**Issue by UberJason** [moritzmhmk/homebridge-camera-rpi#20]
Hi there, this is an amazing plugin! It's awesome to be able to view a live stream of my Pi camera from the Home app on my iPhone. However, I noticed that I can't view the camera from two sources at the same time - for example, if I'm viewing the camera stream in the Home app on my iPhone, I can't see it in the Home app on my iPad. When I close the Home app on my iPhone, then the stream starts working on the iPad. 

Just wondering if this is a known issue or limitation of the camera or your plugin, or if I've got something wonky in my setup and simultaneously viewing should be possible?

**Comment by moritzmhmk** [comment]
It is a known limitation. Viewing the stream starts ffmpeg which binds to the camera. No other program (and no second ffmpeg instance) can access the camera now. The non-live preview images also do not update while the stream is being watched for the same reason.

If you find a way to allow multiple ffmpeg instances to access a single video device or to create virtual video devices that mirror the real device this could be solved. I did a bit of research without success.

**Comment by UberJason** [comment]
Cool, thank you for the info!
