### ISSUE TITLE
options in config.json aren't recognized in homebridge mode

### ISSUE THREAD

**Issue by thymjan** [moritzmhmk/homebridge-camera-rpi#23]
I tried to set options ("rotation": 180) in homebridge mode (not standalone).
The options mentioned in the "cameras"-line in the "platforms"-part are not recognized. Always the default values from the CameraAccessory.js-file are used.

First part of the config.json is parsed an set up correctly (the "bridge"-part).

```
{
        "bridge": {
                "name": "cambridge",
                "username": "CC:75:4D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "description": "This is the description",

        "platforms": [
                {
                "platform": "rpi-camera",
                "cameras": [{"name": "Pi Camera", "id": "Pi Camera", "rotation": 180}]
                }
                ]
}
```

**Comment by tokamac** [comment]
Hi, try:
`"rotate": 180`
instead of:
`"rotation": 180`

**Comment by moritzmhmk** [comment]
read the README of this repo, the documentation on npmjs is not updated yet - will be fixed soon.

**Comment by thymjan** [comment]
Thanks for the fast help and the great work!
