### ISSUE TITLE
No image received

### ISSUE THREAD

**Issue by orilpik** [moritzmhmk/homebridge-camera-rpi#25]
Hi, thanks for making this plugin. I think that I have done well all the steps, but when I run homebridge and after I have added the Pi Cam, and the icon is visible in the Home app, I get this at the terminal

 dev connected 0x000000000371c36e true
-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
ffmpeg ffmpeg version 3.2.10-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared

ffmpeg   libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100

ffmpeg [video4linux2,v4l2 @ 0xbf4620] Cannot open video device /dev/video0: No such file or directory

ffmpeg /dev/video0: No such file or directory

Any Idea? I use the Pi NoIR Camera V2
Thank you very much!

**Comment by thymjan** [comment]
Check your physical connection to your camera once again. Did you enable it with raspi-conf? Do the raspicam tutorial on raspberrypi.org to be shure everything is connected the right way.

**Comment by orilpik** [comment]
Hi @thymjan ! Thank you mate! It was that I don’t pressed enough the connector of the camera module. I thought that If I press more I could break the cable! Thank you!!!
