### ISSUE TITLE
Any chance 1080p support might return?

### ISSUE THREAD

**Issue by Squuiid** [moritzmhmk/homebridge-camera-rpi#33]
@moritzmhmk I see that the release notes for v0.0.2 show that 1080p support was removed due to cropping issues.
Is there any chance this might be fixed or is it just not possible at this stage? It's the only thing stopping this plugin from being absolutely perfect :)

    video: {
      resolutions: [
        // [1920, 1080, 30], // Width, Height, framerate
        // [1280, 960, 30],
        [1280, 720, 30],
        [1024, 768, 30],
        [640, 480, 30],
        [640, 360, 30],
        [480, 360, 30],
        [480, 270, 30],
        [320, 240, 30],
        [320, 240, 15], // Apple Watch requires this configuration
        [320, 180, 30]

**Comment by moritzmhmk** [comment]
the pi camera supports 1080p only in a "zoomed in"/cropped mode - so there is probably no way to fix this

**Comment by Squuiid** [comment]
Ah I see, that’s a shame. Thank you for the quick reply and thank you very much for making this great plugin for HomeBridge.

**Comment by Squuiid** [comment]
If I wanted to enable it to take a look would I just have to remove the // from the configvshown above?
