### ISSUE TITLE
Black rectangle on Home.app screenshots

### ISSUE THREAD

**Issue by jankais3r** [moritzmhmk/homebridge-camera-rpi#36]
When I take a screenshot of the Home app, there is just a black rectangle in place of the actual camera stream. It's similar to how Netflix blacks the screen when you try to screenshot it. When I record my screen, the camera stream is visible as it should be.
https://imgur.com/a/C3xupO2

Anyone else experiencing this? I am on the latest iOS 12 beta and this is my first HomeKit-compatible camera, so I am not sure if this is an expected behavior, but I definitely previously saw screenshots online with a camera stream instead of the black rectangle.

**Comment by Fasani** [comment]
@jankais3r you mean when you press Home + Side Button? I will test when I get home if no one else has a chance to before then. I am on iOS 11.4.1.

**Comment by moritzmhmk** [comment]
Is this solved? On my iPhone SE with iOS 12 screenshots work fine.

**Comment by jankais3r** [comment]
Confirm solved on iOS 12 GM.
