### ISSUE TITLE
Release new version to NPM

### ISSUE THREAD

**Issue by aaronpearce** [moritzmhmk/homebridge-camera-rpi#40]
Can we get a new NPM release that includes the recent fixes?

**Comment by zeromancer1972** [comment]
You may install it directly from git with
```npm install moritzmhmk/homebridge-camera-rpi#master```

**Comment by aaronpearce** [comment]
Yep, but that’s not convenient or clear to the vast majority of users of the package. Given the updates we’re done months ago, npm should have an update.

**Comment by zeromancer1972** [comment]
I agree, especially when you let the config-ui-x do the work

**Comment by moritzmhmk** [comment]
v0.0.4 is released but I cant test it right now - please report any issues here!

**Comment by fr3nch13** [comment]
Just an FYI.

For me an `npm update -g homebridge-camera-rpi ` didn't update it, so I had to do an `nom I -g homebridge-camera-rpi`.
I'm new to npm, but know apt/yum, so I was expecting that to work.

**Comment by aaronpearce** [comment]
Going to mark this closed as well it's out.
