### ISSUE TITLE
Support for pseudo motion detection?

### ISSUE THREAD

**Issue by fr3nch13** [moritzmhmk/homebridge-camera-rpi#42]
So, I forked this to see if I could include a motion detection accessory in this package without any extra hardware (like the ir sensor).

I was thinking of doing it like so:

- Take a snapshot every second and save it to the hd like current.jpg.
- Take a snapshot 1 second later, move the current.jpg to past.jpg, and save this one to current.jpg
- Use ssdeep (fuzzy hashing) to hash both the current and past files.
- Use ssdeep to compare the hashes.
- If the files are more than `config['sensative_setting']` different, than mark the motion sensor as triggered?

Would anyone be interested in this?

**Comment by jonerikandersen** [comment]
Yes, I would. Because then the motion trigger could activate lights or other actions.

**Comment by miguelans** [comment]
Yes, I’d be interested!
