### ISSUE TITLE
Support for remote viewing

### ISSUE THREAD

**Issue by robgjansen** [moritzmhmk/homebridge-camera-rpi#48]
I'm running the standalone installation as a service on my rpi zero w. It works great while I connect over wifi, but when I disable wifi and try to connect over my wireless phone connection I can't see the stream or any still images. (I am using a HomePod to allow remote access to my devices.)

Is this a known limitation? Is there any planned support for remote viewing? Thank you!

**Comment by galliangg** [comment]
The remote viewing works for me, both on my phone and Apple Watch. 

I have an Apple TV for the remote access

**Comment by robgjansen** [comment]
@galliangg interesting! Can you confirm that you have the standalone version installed? Thank!

**Comment by galliangg** [comment]
I’m using this image

https://github.com/moritzmhmk/buildroot-camera-rpi/releases/download/v0.0.2/camera-rpi-v0.0.2.img.zip.zip

On a rpi zero w

I’m watching the camera now away from my house

**Comment by robgjansen** [comment]
OK, so my guess is that the image contains the full version and not the standalone version.

As I mentioned, I installed the standalone version. Here are the steps I followed:
http://www.breaknormal.com/2019-02-20-diy-apple-homekit-camera-with-raspberry-pi

I'm still wondering if there is any planned support for remote viewing when using the standalone version? Thank you!

**Comment by moritzmhmk** [comment]
The image uses the standalone version. The “non-standalone” version is not a “full” version. It is the same code designed for use as a homebridge plugin.

The image works fine for me. Remote viewing works with macOS and iOS.

Is there anything special about your home network that might cause remote viewing to fail? What kind of device do you use as the home hub?

**Comment by robgjansen** [comment]
Thanks for the clarification!

Yeah, I think my HomePod _should_ work fine. I am able to toggle all of my homekit light switches remotely - those are on the same wifi network with the same HomePod.

I have this set up on a raspberry pi zero w, but I don't see how that would affect remote viewing.

I guess a reasonable next step would be for me to try the image version that you released and see if that works. If it does, then I guess that points to some issue in my manual setup (as mentioned, outlined [here](http://www.breaknormal.com/2019-02-20-diy-apple-homekit-camera-with-raspberry-pi)).
