### ISSUE TITLE
Throw exception when try to view video on iPhone

### ISSUE THREAD

**Issue by mickey9801** [moritzmhmk/homebridge-camera-rpi#5]
After installed homebridge-camera-pi, I registered the Pi camera on my iPhone and tried to view video on iPhone. I am using a static build of ffmpeg. I have installed libv4l-dev and v4l-utils on the  Raspberry Pi before for using OpenCV.

The error message is as below:

--set-ctrl video_bitrate=299000
-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -vcodec copy -an -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params U4D3ysXeVgkvsrgN8PEbwem3gbr4WdPxWv7cX1Zl srtp://192.168.1.101:54117?rtcpport=54117&localrtcpport=54117&pkt_size=1378
internal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:369:9)
    at Camera.handleStreamRequest (/opt/homebridge-camera-rpi/CameraSource.js:180:18)
    at StreamController._handleStartStream (/opt/homebridge-camera-rpi/node_modules/hap-nodejs/lib/StreamController.js:437:21)
    at StreamController._handleSelectedStreamConfigurationWrite (/opt/homebridge-camera-rpi/node_modules/hap-nodejs/lib/StreamController.js:298:12)
    at .<anonymous> (/opt/homebridge-camera-rpi/node_modules/hap-nodejs/lib/StreamController.js:262:12)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/opt/homebridge-camera-rpi/node_modules/hap-nodejs/lib/Characteristic.js:292:10)

**Comment by moritzmhmk** [comment]
Is the user executing homebridge member of the `video` group?

**Comment by mickey9801** [comment]
no. I am using pi to execute homebridge

**Comment by moritzmhmk** [comment]
try adding pi to the `video` group (and reboot)

**Comment by mickey9801** [comment]
Just tried, but the exception still thrown. The error message changed a bit.

-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
internal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:369:9)
    at Camera.handleSnapshotRequest (/usr/lib/node_modules/homebridge-camera-rpi/CameraSource.js:63:16)
    at Accessory._handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:864:25)
    at emitTwo (events.js:106:13)
    at HAPServer.emit (events.js:191:7)
    at HAPServer._handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:1033:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)

**Comment by moritzmhmk** [comment]
It is the command for taking a preview snapshot this time. Can `pi` execute the `ffmpeg` command? It is some sort of access error (EACCES) and my first thought was no access to the camera hardware but that should be fine now.

**Comment by mickey9801** [comment]
yes, I placed it in /usr/local/bin/ffmpeg/ directory. I can execute `/usr/local/bin/ffmpeg/ffmpeg -version` to obtain version information.

I can run raspistill to capture a photo.

**Comment by moritzmhmk** [comment]
does `which ffmpeg`  return `/usr/local/bin/ffmpeg/ffmpeg`?

**Comment by mickey9801** [comment]
Oh, after I put /usr/local/bin/ffmpeg/ffmpeg to PATH, it works now. Thank you for your kindly help.

**Comment by mickey9801** [comment]
Sorry I found that it is not working quite well. It cannot not stream a video to iPhone and always stopped response after about 50 second. But once I close the video screen, It will update the thumbnail to latest view.

**Comment by mickey9801** [comment]
The terminal showing these message in a period of time:

-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
ffmpeg ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg

ffmpeg   libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

ffmpeg Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: -140459422.189768, bitrate: N/A

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 480x270 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1000k tbn, 1000k tbc

ffmpeg Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help

ffmpeg Output #0, mjpeg, to 'pipe:':
  Metadata:
    encoder         : Lavf57.83.100

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc), 480x270 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1

ffmpeg frame=    1 fps=0.0 q=3.0 Lsize=       5kB time=00:00:00.03 bitrate=1327.5kbits/s speed=1.58x
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by mickey9801** [comment]
I found the pattern the stream not start correctly: It will correctly start streaming if there is NO LIGHT in the scene. After the stream started, I can turn on the light and the stream will continue. But if I tried to view the video when light is up, it will not begin the stream correctly and finally timeout.

**Comment by moritzmhmk** [comment]
Can `pi` execute `v4l2-ctl`?

**Comment by mickey9801** [comment]
yes. The output is like this:
pi@rpi302:~ $ v4l2-ctl --all
Driver Info (not using libv4l2):
	Driver name   : bm2835 mmal
	Card type     : mmal service 16.1
	Bus info      : platform:bcm2835-v4l2
	Driver version: 4.9.35
	Capabilities  : 0x85200005
		Video Capture
		Video Overlay
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x05200005
		Video Capture
		Video Overlay
		Read/Write
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 0: ok)
Format Video Capture:
	Width/Height  : 1024/768
	Pixel Format  : 'JPEG'
	Field         : None
	Bytes per Line: 0
	Size Image    : 786432
	Colorspace    : JPEG (JFIF/ITU601)
	Flags         :
...

**Comment by moritzmhmk** [comment]
what bitrate is set? It seems as if homebridge cant use v4l2-ctl to set the bitrate...

**Comment by mickey9801** [comment]
I just setup as README say. Where can I set the bitrate?

**Comment by moritzmhmk** [comment]
`v4l2-ctl --set-ctrl video_bitrate=300000`

**Comment by mickey9801** [comment]
I have just try the command and then start homebridge, but it cannot fix the problem. It is still timeout if there are any light when I click the camera on home app, and if I cover the lens with my finger before I click the camera, it will start streaming correctly.

**Comment by moritzmhmk** [comment]
what was the (full) output when executing the command?

**Comment by mickey9801** [comment]
Here is the log of all stdout and stderr (if any).

There are total 4 video4linux2 session in this test. The first one (from line 51) is the initial session when start up Home app, which obtain a still shot for home screen. The second session (from line 90) is the "timeouted" session. It timeout after about 30 second but nothing show in the terminal. The third session (from line 105) is the still shot I end the last session and go back to home. And the forth session (from 141) is the good session that can stream correctly.

```-- homebridge log --
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/13/2017, 9:07:47 AM] Loaded plugin: homebridge-camera-rpi
[11/13/2017, 9:07:48 AM] Registering platform 'homebridge-camera-rpi.rpi-camera'
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loaded plugin: homebridge-dummy
[11/13/2017, 9:07:48 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loaded plugin: homebridge-gpio-wpi2
[11/13/2017, 9:07:48 AM] Registering platform 'homebridge-gpio-wpi2.WiringPiPlatform'
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loaded plugin: homebridge-info
[11/13/2017, 9:07:48 AM] Registering platform 'homebridge-info.Info'
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loaded plugin: homebridge-raspberrypi-temperature
[11/13/2017, 9:07:48 AM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loaded config.json with 2 accessories and 2 platforms.
[11/13/2017, 9:07:48 AM] ---
[11/13/2017, 9:07:48 AM] Loading 2 platforms...
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Initializing WiringPiPlatform platform...
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] WORK IN PROGRESS... Report issues on https://github.com/rsg98/homebridge-gpio-wpi2
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Exporting GPIO Pins from config file...
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Exporting and configuring: GPIO4
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Exporting and configuring: GPIO5
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Exporting and configuring: GPIO6
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] homebridge API version: 2.2
[11/13/2017, 9:07:48 AM] [rpi-camera] Initializing rpi-camera platform...
[11/13/2017, 9:07:48 AM] Loading 2 accessories...
[11/13/2017, 9:07:48 AM] [lamp] Initializing DummySwitch accessory...
[11/13/2017, 9:07:48 AM] [RaspberrtPiTemperature] Initializing RaspberryPiTemperature accessory...
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] GPIO4 Configure GPIO Pin 251b9283-dc24-4df2-a871-0c005005e67d
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Turning off pin #23
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] GPIO5 Configure GPIO Pin ffd23143-b8b9-4fa0-b957-cc5ed3a0eb30
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Turning off pin #24
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] GPIO6 Configure GPIO Pin 98ab461c-938d-48b8-95d2-4de69fae94cf
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Turning off pin #25
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ???-??-??? │     
    └────────────┘     
                       
[11/13/2017, 9:07:48 AM] [Pi GPIO (WiringPi)] Loading cached GPIO pins complete
[11/13/2017, 9:07:48 AM] Homebridge is running on port 44318.
[11/13/2017, 9:07:48 AM] Pi Camera is running on port 36853.
-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
ffmpeg ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg

ffmpeg   libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100

ffmpeg   libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

ffmpeg Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: -140462265.666660, bitrate: N/A

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 480x270 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1000k tbn, 1000k tbc

ffmpeg Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help

ffmpeg [mjpeg @ 0x372e380] removing common factors from framerate

ffmpeg Output #0, mjpeg, to 'pipe:':
  Metadata:
    encoder         : Lavf57.83.100

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc), 480x270 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1

ffmpeg frame=    1 fps=0.0 q=3.5 Lsize=       8kB time=00:00:00.03 bitrate=1900.6kbits/s speed=0.28x    
video:8kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

--set-ctrl video_bitrate=299000
-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -vcodec copy -an -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Qtib3Y0MMQHFzIiX9Xr947karroOU5tM+nqez3ZF srtp://192.168.1.101:63552?rtcpport=63552&localrtcpport=63552&pkt_size=1378
ffmpeg ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg

ffmpeg   libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

-f video4linux2 -input_format mjpeg -video_size 480x270 -i /dev/video0 -vframes 1 -f mjpeg -
ffmpeg ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg

ffmpeg   libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

ffmpeg Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: -140462232.303955, bitrate: N/A

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 480x270 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1000k tbn, 1000k tbc

ffmpeg Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help

ffmpeg Output #0, mjpeg, to 'pipe:':
  Metadata:
    encoder         : Lavf57.83.100

ffmpeg     Stream #0:0: Video: mjpeg, yuvj420p(pc), 480x270 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1

ffmpeg frame=    1 fps=0.0 q=3.5 Lsize=       8kB time=00:00:00.03 bitrate=1909.5kbits/s speed=2.13x    
video:8kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

--set-ctrl video_bitrate=299000
-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -vcodec copy -an -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params MUj0gR10IzlwYhQi9uK7+BAdcZWTVKhhuxTWjwa/ srtp://192.168.1.101:55420?rtcpport=55420&localrtcpport=55420&pkt_size=1378
ffmpeg ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg

ffmpeg   libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

ffmpeg Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 383.965774, bitrate: N/A

ffmpeg     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 1000k tbn, 2000k tbc

ffmpeg Output #0, rtp, to 'srtp://192.168.1.101:55420?rtcpport=55420&localrtcpport=55420&pkt_size=1378':
  Metadata:
    encoder         : Lavf57.83.100

ffmpeg     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, q=2-31, 30 fps, 30 tbr, 90k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[rtp @ 0x2a0b1a0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

ffmpeg frame=   23 fps=0.0 q=-1.0 size=       5kB time=00:00:00.69 bitrate=  63.1kbits/s speed=1.37x    
ffmpeg frame=   38 fps= 37 q=-1.0 size=      12kB time=00:00:01.19 bitrate=  80.0kbits/s speed=1.18x    
ffmpeg frame=   53 fps= 35 q=-1.0 size=      18kB time=00:00:01.69 bitrate=  86.2kbits/s speed=1.11x    
ffmpeg frame=   69 fps= 34 q=-1.0 size=      24kB time=00:00:02.23 bitrate=  87.2kbits/s speed= 1.1x    
ffmpeg frame=   84 fps= 33 q=-1.0 size=      69kB time=00:00:02.73 bitrate= 207.3kbits/s speed=1.08x    
ffmpeg frame=   99 fps= 33 q=-1.0 size=     138kB time=00:00:03.23 bitrate= 350.9kbits/s speed=1.06x    
ffmpeg frame=  114 fps= 32 q=-1.0 size=     163kB time=00:00:03.73 bitrate= 358.5kbits/s speed=1.05x    
ffmpeg frame=  129 fps= 32 q=-1.0 size=     180kB time=00:00:04.23 bitrate= 347.9kbits/s speed=1.05x    
ffmpeg frame=  144 fps= 32 q=-1.0 size=     191kB time=00:00:04.73 bitrate= 330.6kbits/s speed=1.04x    
ffmpeg frame=  159 fps= 31 q=-1.0 size=     203kB time=00:00:05.23 bitrate= 318.5kbits/s speed=1.04x    
ffmpeg frame=  174 fps= 31 q=-1.0 size=     217kB time=00:00:05.73 bitrate= 310.2kbits/s speed=1.03x    
ffmpeg frame=  190 fps= 31 q=-1.0 size=     235kB time=00:00:06.26 bitrate= 306.7kbits/s speed=1.03x    
ffmpeg frame=  205 fps= 31 q=-1.0 size=     252kB time=00:00:06.76 bitrate= 304.7kbits/s speed=1.03x    
ffmpeg frame=  220 fps= 31 q=-1.0 size=     270kB time=00:00:07.26 bitrate= 304.1kbits/s speed=1.03x    
ffmpeg frame=  235 fps= 31 q=-1.0 size=     289kB time=00:00:07.76 bitrate= 305.2kbits/s speed=1.03x    
ffmpeg frame=  250 fps= 31 q=-1.0 size=     312kB time=00:00:08.26 bitrate= 309.5kbits/s speed=1.02x    ```

**Comment by moritzmhmk** [comment]
You could try running https://github.com/moritzmhmk/buildroot-camera-rpi to make sure that it is not a hardware problem.

**Comment by pokono** [comment]
Did you solve this? I have the same behaviour happening on my pi. No hardware problem, but I do have an openvpn server and pi-hole installed on the same pi.

**Comment by moritzmhmk** [comment]
Which of the problems do you encounter? What happens when using [buildroot-camera-rpi](https://github.com/moritzmhmk/buildroot-camera-rpi)?

**Comment by pokono** [comment]
@moritzmhmk I felt like it was more appropriate to open up another issue to be able to explain better! I opened up #9.
