### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by ammartist** [moritzmhmk/homebridge-camera-rpi#55]
Hi,

I am geting DeprecationWarning when trying to install it:

# npm install -g homebridge-camera-rpi
(node:1196) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
homebridge-camera-rpi@0.0.4 /usr/local/lib/node_modules/homebridge-camera-rpi
└── ip@1.1.5

is it Deprecated and gone for ever? ;-(

**Comment by moritzmhmk** [comment]
It should still work just fine, it just warns that one of the dependencies is using a method that is deprecated (i.e. this method will not be available soon).

This warning will probably be fixed by the next release using updated dependencies.

**Comment by ammartist** [comment]
@moritzmhmk Thanks for the reply!
when i try to installing it all i get is that line.. is there a special way to install it?

**Comment by moritzmhmk** [comment]
what is the output of ``npm list -g --depth 0``

**Comment by ammartist** [comment]
(node:5736) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/lib
└── homebridge-camera-rpi@0.0.4

**Comment by moritzmhmk** [comment]
and ``npm -v``?

It looks like there is something outdated with your npm or node installation.

But it should not affect homebridge-camera-rpi, which according to that output did install properly.

**Comment by ammartist** [comment]
1.4.21
(node:5765) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by moritzmhmk** [comment]
npm 1.4.21 is about 5 years old. Consider installing an up to date version of node and npm.

Instructions can be found [here](https://github.com/nodesource/distributions#deb).

If you use a Raspberry Pi B, B+ or Zero google for an up to date tutorial on installing without the package manager. The latest release for armv6 seems to be [11.x](https://nodejs.org/dist/latest-v11.x/) (for [12.x](https://nodejs.org/dist/latest-v12.x/) there are no builds for this arch)

Even without installing an up to date version (which I highly recommend anyway!) homebridge-camera-rpi should work and your installation has been successfull so far just yielding that confusing deprecation warning.

**Comment by ammartist** [comment]
I am using pi 3B and HOOBS Release... however this means they are using outdated packages ... 

Thank you so much ;-)
