### ISSUE TITLE
Increase bitrate and FPS

### ISSUE THREAD

**Issue by Cavas17** [moritzmhmk/homebridge-camera-rpi#70]
Hi,

Is there a way to increase bitrate and/or FPS please ?

Thanks !

**Comment by moritzmhmk** [comment]
See issue #44 on increasing the bitrate.

**Comment by Cavas17** [comment]
Thanks for answer.

But what syntax do you use to change this line. For a 800k bitrate for example ?

**Comment by moritzmhmk** [comment]
Replace `${bitrate}` with 800. This overrides the requested bitrate. If you just want to increase the default bitrate change `bitrate = 300` a few lines above.

**Comment by Cavas17** [comment]
Ok. Thanks a lot.
