### ISSUE TITLE
Can't Live Stream Within Local Network

### ISSUE THREAD

**Issue by pokono** [moritzmhmk/homebridge-camera-rpi#9]
This is a weird issue, I'll try to explain the best I can.

I have homebridge installed on a Raspberry Pi 3 connected over LAN. On the Raspberry I also have configured OpenVPN and Pi Hole.
Additionally in my setup I have an Apple TV configured in HomeKit.

Raspberry Pi IP: 192.168.2.200 (static)
Apple TV IP: 192.168.2.2 (can change, lease time is a year)

I'm able to live stream the camera on my iPhone from an LTE connection but now over WiFi within the local network (when I'm in the house).
I can see the picture updating just fine (every 10 seconds) in both LTE and WiFi.

I can see the logs, which are identical when streaming LTE vs WiFi.
LTE:
```
ffmpeg Output #0, rtp, to 'srtp://192.168.2.2:58133?rtcpport=58133&localrtcpport=58133&pkt_size=1378':
```
Stream starts in the logs, iPhone shows loading for a couple of seconds and then I'm able to see the stream live.
WiFi (local network):
```
ffmpeg Output #0, rtp, to 'srtp://192.168.2.15:51196?rtcpport=51196&localrtcpport=51196&pkt_size=1378':
```
Stream starts in the logs (identical to LTE beside IP and resolution), iPhone shows loading for about 30 seconds and then it tells me that the camera is not available.

I can't figure it out why I cannot live stream from within the local network.
Can anybody point me in the right direction?

Thank you!

**Comment by moritzmhmk** [comment]
This is probably an issue with your network. You may want to try this on some other network to confirm this. Is there anything special about your setup?

**Comment by pokono** [comment]
I ended up setting up 2 additional Pi Zero /W with as cameras with their own homebridge and plugin. It's been working great.

The only difference about the above setup is that homebridge-camera-rpi is running on the same box as pi.hole and pivpn. My guess is that because the network uses the same box as DNS server the Apple TV has trouble finding the camera for live streaming.
I'm gonna close this as I'm not able to do further tries.
